apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: outfitstyle
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: FIREBASE_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: firebase-credentials-secret
              key: credentials.json
        volumeMounts:
        - name: firebase-credentials
          mountPath: /etc/firebase
          readOnly: true
      volumes:
      - name: firebase-credentials
        secret:
          secretName: firebase-credentials-secret
