apiVersion: v1
kind: Namespace
metadata:
  name: outfitstyle
  labels:
    name: outfitstyle
    # Istio sidecar auto-injection
    # istio-injection: enabled
    # Установите label после установки Istio:
    #   kubectl label namespace outfitstyle istio-injection=enabled
