# ServiceMonitor для API
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-servicemonitor
  namespace: outfitstyle
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
# ServiceMonitor для ML-сервиса
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-service-servicemonitor
  namespace: outfitstyle
  labels:
    app: ml-service
spec:
  selector:
    matchLabels:
      app: ml-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s