import '../entities/app_settings.dart';

abstract class ISettingsRepository {
  Future<AppSettings> getSettings();
  Future<void> updateSettings(AppSettings settings);
  Future<void> resetToDefaults();
  Future<bool> isNotificationsEnabled();
  Future<void> setNotificationsEnabled(bool enabled);
  Future<bool> isLocationEnabled();
  Future<void> setLocationEnabled(bool enabled);
  Future<bool> isAnalyticsEnabled();
  Future<void> setAnalyticsEnabled(bool enabled);
  Future<bool> isDarkMode();
  Future<void> setDarkMode(bool enabled);
  Future<String> getTemperatureUnit();
  Future<void> setTemperatureUnit(String unit);
  Future<String> getDistanceUnit();
  Future<void> setDistanceUnit(String unit);
  Future<String> getCurrency();
  Future<void> setCurrency(String currency);
  Future<String> getLanguage();
  Future<void> setLanguage(String language);
  Future<bool> isAutoSync();
  Future<void> setAutoSync(bool enabled);
  Future<int> getSyncInterval();
  Future<void> setSyncInterval(int minutes);
  Future<bool> isPremiumFeaturesEnabled();
  Future<void> setPremiumFeaturesEnabled(bool enabled);
  Future<String> getTheme();
  Future<void> setTheme(String theme);
  Future<bool> isHapticFeedbackEnabled();
  Future<void> setHapticFeedbackEnabled(bool enabled);
  Future<bool> isSoundEffectsEnabled();
  Future<void> setSoundEffectsEnabled(bool enabled);
  Future<String?> getLastSync();
  Future<void> setLastSync(String timestamp);
  Future<bool> isShowWeatherOnHome();
  Future<void> setShowWeatherOnHome(bool enabled);
  Future<bool> isShowRecommendationsOnHome();
  Future<void> setShowRecommendationsOnHome(bool enabled);
  Future<bool> isAutoRefreshWeather();
  Future<void> setAutoRefreshWeather(bool enabled);
  Future<int> getWeatherRefreshInterval();
  Future<void> setWeatherRefreshInterval(int minutes);
  Future<bool> isEnableOfflineMode();
  Future<void> setEnableOfflineMode(bool enabled);
  Future<bool> isAllowPersonalizedAds();
  Future<void> setAllowPersonalizedAds(bool enabled);
}