// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLgPQvZs3JFCDn9Gm5ZJYmS1XZ6xPYqKg',
    appId: '1:242419520610:web:8a2f8b5c9d3e4f6a7b8c9d',
    messagingSenderId: '242419520610',
    projectId: 'outfitstyle-ce15f',
    authDomain: 'outfitstyle-ce15f.firebaseapp.com',
    storageBucket: 'outfitstyle-ce15f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgPQvZs3JFCDn9Gm5ZJYmS1XZ6xPYqKg',
    appId: '1:242419520610:android:8a2f8b5c9d3e4f6a7b8c9d',
    messagingSenderId: '242419520610',
    projectId: 'outfitstyle-ce15f',
    storageBucket: 'outfitstyle-ce15f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgPQvZs3JFCDn9Gm5ZJYmS1XZ6xPYqKg',
    appId: '1:242419520610:ios:8a2f8b5c9d3e4f6a7b8c9d',
    messagingSenderId: '242419520610',
    projectId: 'outfitstyle-ce15f',
    storageBucket: 'outfitstyle-ce15f.appspot.com',
    iosBundleId: 'com.app.outfitstyle',
  );
}
